#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.vdo"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.vdo" "${2}"
        fi
        
        # build modules and load them
        omv-mkconf vdo
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
